-- Create the tasks table
create table tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  text text check (char_length(text) > 0),
  is_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add a comment to the table
comment on table tasks is 'Stores to-do tasks for each user.';
-- Enable Row Level Security for the tasks table
alter table tasks enable row level security;

-- Create a policy that allows users to view their own tasks
create policy "Users can view their own tasks." on tasks
  for select using (auth.uid() = user_id);

-- Create a policy that allows users to insert their own tasks
create policy "Users can insert their own tasks." on tasks
  for insert with check (auth.uid() = user_id);

-- Create a policy that allows users to update their own tasks
create policy "Users can update their own tasks." on tasks
  for update using (auth.uid() = user_id);

-- Create a policy that allows users to delete their own tasks
create policy "Users can delete their own tasks." on tasks
  for delete using (auth.uid() = user_id);
